# Welcome to Jekyll!
# Site settings
title: Hannah Barudin
description: My personal site
email: hbarudin@gmail.com
github_username: hbarudin
baseurl: ""
url: "https://hbarudin.com"

# Build settings
theme: minima
plugins:
  - jekyll-feed
